### PR TITLE
Add camera page

### PR DESCRIPTION
**Pull request by heytulsiprasad**
# Description

- Adds the capture bookshelf by using device camera option. Scanning through QR code feature is yet to be added.

**New dependency:**

- [react-webcam](https://www.npmjs.com/package/react-webcam)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by heytulsiprasad** [comment]
@Akshay090 you can have a look and merge ✌️

**Review by Akshay090 — CHANGES_REQUESTED** [review]
good work @heytulsiprasad with qr and screenshot. 
I did check out the code and this I observed. 
* The /capture page didn't work on my mobile phone (do check at your end also)
* It's currently a route, instead it should be a popup that appears on clicking scan btn on profile page.

**Comment by heytulsiprasad** [comment]
Thanks @Akshay090, couple thoughts on first look:

- The `getUserMedia/Stream API` is supported on these [devices](https://caniuse.com/stream).
- `react-webcam`'s docs says, *"browsers will throw an error if the page is loaded from insecure origin (use https)"*

Also, I deployed a local branch to vercel today, here's a screenshot how it looked on my mobile. [Deployment link](https://new-book-shelf-demo.vercel.app/capture)

image

If all is good, I can start shifting this route inside a popup component as shown in the mockup. 

Thanks.

**Comment by Akshay090** [comment]
@heytulsiprasad awesome, yes you should implement it in popup 👍

**Comment by heytulsiprasad** [comment]
Hey @Akshay090, added a few changes.

- Modal effect on *Capture Bookshelf* button 
- Feedback to user on taking certain actions, using toasts

Lemme know your thoughts.

**Comment by heytulsiprasad** [comment]
Also could you add either Netlify/Vercel so we can get live preview links for each PR? I have to manually do that from my side 😢

**Pull request merged**
